### ISSUE TITLE
Doc fix: install instructions specify go 1.14 but modules depend on at least 1.15

### ISSUE THREAD

**Issue by eharris** [rclone/rclone#5809]
From the install instructions at https://rclone.org/install/
Go version 1.14 is required to build from source.  However dependency requirements require at least 1.17:

```
# github.com/rclone/rclone/fs
fs/versioncheck.go:8:15: undefined: Go_version_1_15_required_for_compilation
note: module requires Go 1.17
# github.com/golang-jwt/jwt/v4
../../../../pkg/mod/github.com/golang-jwt/jwt/v4@v4.1.0/ecdsa.go:135:4: r.FillBytes undefined (type *big.Int has no field or method FillBytes)
../../../../pkg/mod/github.com/golang-jwt/jwt/v4@v4.1.0/ecdsa.go:136:4: s.FillBytes undefined (type *big.Int has no field or method FillBytes)
note: module requires Go 1.15
# golang.org/x/net/http2
../../../../pkg/mod/golang.org/x/net@v0.0.0-20211109214657-ef0fda0de508/http2/transport.go:417:45: undefined: os.ErrDeadlineExceeded
note: module requires Go 1.17
```

**Comment by eharris** [comment]
It should be noted that the install instructions (when using go 1.17) also issue the following warning:

```
> go get github.com/rclone/rclone
go get: installing executables with 'go get' in module mode is deprecated.
        Use 'go install pkg@version' instead.
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
```

**Comment by albertony** [comment]
Thank you for reporting!

The minimum is 1.15 according to this: https://github.com/rclone/rclone/commit/c968c3e41cf71896f50f6b4a5c3cc5ffd5e7fa35

> This was necessary because go1.14 seems to have a modules related bug which means it tries to build modules even though the uses of them are all disabled with build constraints.

Don't know if the `note: module requires Go 1.17` message is misleading and caused by the above mentioned bug?

Do you want to supply a pull request for this yourself? The source is here:

https://github.com/rclone/rclone/blob/master/docs/content/install.md

**Comment by ncw** [comment]
The main webpage and the master branch are out of sync and will be until the next release.

However you can preview the next release docs here

https://tip.rclone.org/install/#install-from-source

which do state go1.15 as a minimum.

If you checkout v1.57.0 then it will build with go1.14

> github.com/rclone/rclone/fs
> fs/versioncheck.go:8:15: undefined: **Go_version_1_15_required_for_compilation**

This is rclone's version check and you should trust this one.

> note: module requires Go 1.17
> github.com/golang-jwt/jwt/v4
> ../../../../pkg/mod/github.com/golang-jwt/jwt/v4@v4.1.0/ecdsa.go:135:4: r.FillBytes undefined (type *big.Int has no field or method FillBytes)
> ../../../../pkg/mod/github.com/golang-jwt/jwt/v4@v4.1.0/ecdsa.go:136:4: s.FillBytes undefined (type *big.Int has no field or method FillBytes)
> note: module requires Go 1.15
> golang.org/x/net/http2
> ../../../../pkg/mod/golang.org/x/net@v0.0.0-20211109214657-ef0fda0de508/http2/transport.go:417:45: undefined: os.ErrDeadlineExceeded
> note: module requires Go 1.17

These, as far as I can see, are spurious messages from go1.14

**Comment by ncw** [comment]
> It should be noted that the install instructions (when using go 1.17) also issue the following warning:
> 
> ```
> > go get github.com/rclone/rclone
> go get: installing executables with 'go get' in module mode is deprecated.
>         Use 'go install pkg@version' instead.
>         For more information, see https://golang.org/doc/go-get-install-deprecation
>         or run 'go help get' or 'go help install'.
> ```

We should fix this in the docs, perhaps have a pre go1.17 and post section?

**Comment by albertony** [comment]
> which do state go1.15 as a minimum.

I totally overlooked that! 😞
