### ISSUE TITLE
Proton Drive: segmentation fault with sync

### ISSUE THREAD

**Issue by massoncl** [rclone/rclone#9455]
#### What is the problem you are having with rclone?

`sync` runs into a segmentation fault after a while. Initially the command works, files are being transferred, but at some point it crashes. 

#### What is your rclone version (output from `rclone version`)

```
rclone v1.75.0-beta.9760.be3bfe2d1
- os/version: raspbian 13.5 (64 bit)
- os/kernel: 6.12.75+rpt-rpi-v8 (aarch64)
- os/type: linux
- os/arch: arm (ARMv7 compatible)
- go/version: go1.26.3
- go/linking: static
- go/tags: none
```

(also occurs on 1.74.2)

However, I do not see the issue on another computer running Ubuntu:
```
rclone v1.74.2
- os/version: ubuntu 24.04 (64 bit)
- os/kernel: 6.8.0-40-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.26.3
- go/linking: static
- go/tags: none
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Raspbian, 64 bits

#### Which cloud storage system are you using? (e.g. Google Drive)

Proton Drive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

```
rclone sync "source_path" "Proton Drive:dest_path" --backup-dir "Proton Drive:Trash" --stats-log-level INFO --stats 1m -vv
```

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

The trace is very long so I put it on pastebin: https://pastebin.com/CYt9CjkK 

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
Thanks for the detailed report and the full backtrace :-)

The log starts like this

```
runtime: pointer 0xef4e746 to unused region of span span.base()=0x82ea000 span.limit=0x82ec000 span.state=1
fatal error: found bad pointer in Go heap (incorrect use of unsafe or cgo?)

runtime stack:
runtime.throw({0x284eafd, 0x3e})
	runtime/panic.go:1229 +0x34 fp=0x7ef5e34 sp=0x7ef5e20 pc=0xb233c
runtime.badPointer(0xf7638bf0, 0xef4e746, 0x0, 0x0)
	runtime/mbitmap.go:1334 +0x88 fp=0x7ef5e54 sp=0x7ef5e34 pc=0x3bce4
runtime.findObject(0xef4e746, 0x0, 0x0)
	runtime/mbitmap.go:1386 +0xc8 fp=0x7ef5e6c sp=0x7ef5e54 pc=0xb049c
runtime.scanObjectsSmall(0xc510000, 0x20, 0xf4, 0x785a980, 0x7ef5ed4)
	runtime/mgcmark_greenteagc.go:1056 +0x364 fp=0x7ef5eb8 sp=0x7ef5e6c pc=0x51bf4
runtime.scanSpan(0xc5100f2, 0x785a980)
	runtime/mgcmark_greenteagc.go:897 +0x268 fp=0x7ef5f68 sp=0x7ef5eb8 pc=0x513b0
runtime.gcDrain(0x785a980, 0x3)
	runtime/mgcmark.go:1333 +0x3ac fp=0x7ef5fbc sp=0x7ef5f68 pc=0x4e488
runtime.gcDrainMarkWorkerDedicated(...)
	runtime/mgcmark.go:1178
runtime.gcBgMarkWorker.func2()
	runtime/mgc.go:1862 +0xac fp=0x7ef5fe8 sp=0x7ef5fbc pc=0x48cec
runtime.systemstack(0x80008)
	runtime/asm_arm.s:315 +0x60 fp=0x7ef5fec sp=0x7ef5fe8 pc=0xb89d8
```

That means the crash is an internal problem with Go's garbage collector. Rclone doesn't use cgo when using sync and you aren't using `--use-mmap` so only pure Go code is running with only pure memory management.

The crashing stack is a GC mark worker (`scanObjectsSmall` in `mgcmark_greenteagc.go`) - it found a word in the heap that doesn't point to a valid object and aborted the process. The protondrive/crypto functions you see in the other goroutines are just what happened to be running at the time; they aren't the cause. (The "unsafe or cgo" text is a generic message the runtime always prints for heap corruption - rclone's proton backend uses neither.)

Important things to note:

- The backtrace is **32-bit ARM** (`GOARCH=arm` - all the runtime frames are `asm_arm.s`). Even though your Pi has a 64-bit kernel (`aarch64`), you're running the 32-bit (armhf) build of rclone.
- Go 1.26 ships the new **"Green Tea" garbage collector enabled by default**, and the crash is inside it. It works fine for you on x86_64 with the same Go version, which points at a problem specific to the 32-bit ARM target / GC rather than your data or rclone itself.

First step can you try this 32-bit build with the Green Tea GC turned off built with:

```
GOOS=linux GOARCH=arm GOARM=7 GOEXPERIMENT=nogreenteagc go build
```

https://pub.rclone.org/rclone-linux-armv7-nogreenteagc.zip

If that makes the crash go away, it confirms it's a Green Tea GC bug on 32-bit ARM - in which case it should be reported upstream at https://github.com/golang/go/issues . I'm happy to do that for you if you can confirm the rebuild with the `nogreenteagc` tag fixes the problem.

Next switch to the `arm64` build of rclone. Your kernel is already 64-bit (`aarch64`), and rclone is a static binary with no library dependencies, so the `linux-arm64` build will run fine even if the rest of your OS is 32-bit. Just grab the `arm64` download rather than `arm`/`arm-v7`. The 64-bit GC paths are far more heavily tested and this almost certainly sidesteps the problem. It's also a nice speed-up.

One more thing worth ruling out, since Raspberry Pis are prone to it: please run

```
vcgencmd get_throttled
```

A non-zero result means under-voltage/thermal throttling (often a marginal power supply), which can cause exactly this kind of random memory corruption under load. If you have `memtester` handy, a quick RAM test wouldn't hurt either.

Could you let me know:
1. Whether the `GOEXPERIMENT=nogreenteagc` 32 bit is stable
2. Whether the `arm64` build is stable
3. Whether the hardware tests checked out OK
4. Whether older rclone versions (built with older Go) were stable on this same Pi?

That'll tell us definitively whether this is the Go 1.26 GC on 32-bit or something on the hardware side.

Thank you

**Comment by massoncl** [comment]
Hi, thanks for the quick reply ! 

1. The custom build did not fix the crash. I got slightly different errors (https://pastebin.com/pPvpP29E), but that was also the case for the initial issue, it's always a segfault but the exact message changes. 

2. Switching to the arm64 build seems to fix the issue however ! The install script apparently grabs it by default, so I'm not sure how I ended up with the armv7. 

3. For completeness, the Rpi was not being throttled
4. I didn't try older versions since I only use the Proton Drive backend and that didn't work for a while (thanks for that fix by the way)

**Comment by ncw** [comment]
Thanks for testing all of that so thoroughly - it pins the problem down nicely.

What have we learnt?

- The `nogreenteagc` build still crashing (and the new crash being in the *classic* sweep - "found pointer to free object") means the Green Tea GC isn't the cause after all. The GC is just what detects the corruption; the varying messages are all symptoms of the same underlying heap corruption.
- The arm64 build being stable on the same Pi, with no throttling, rules out bad RAM / power - if it were hardware, the 64-bit build would corrupt too.

So this is a memory-corruption bug specific to the 32-bit ARM build with Go 1.26, not an rclone bug (rclone's Proton backend uses no `unsafe`/cgo, and the corruption is caught inside the Go runtime). The practical fix is exactly what you've done - stay on the `arm64` build. Since your kernel is 64-bit (`aarch64`), that's the right one for your Pi anyway, and it's faster too. The reason the install script gave you `armv7` originally is that it picks the build from your *userland* architecture (32-bit OS gives `armv7l` from `uname -m`), even though the kernel is 64-bit.

If you're willing to do more tests to help get this fixed upstream for other 32-bit users: could you try the 32-bit `arm` rclone built with Go 1.25.10 (instead of 1.26) and see if it's stable?

https://pub.rclone.org/rclone-linux-armv7-nogreenteagc-go1.25.zip

And here is a version compiled with no optimizations

https://pub.rclone.org/rclone-linux-armv7-nogreenteagc-go1.25-no-optimize.zip

There don't seem to be any 100% relevant bugs in the Go bug tracker.

It would be useful to have the output of these also

- `getconf PAGESIZE`
- `uname -a`

How long does it take to reproduce this normally?

What OS do you have installed on your Raspberry Pi? And what kind of Pi is it?

Glad the Proton Drive fix has been working for you otherwise!

**Comment by massoncl** [comment]
The segfault occurs after about 30 seconds, even if no files are being transferred (all skipped because they are unchanged). 

Both binaries with go 1.25 work correctly, at least for a few minutes. 

```getconf PAGESIZE``` : 4096
```uname -a```: ```Linux raspberry 6.12.75+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.12.75-1+rpt1 (2026-03-11) aarch64 GNU/Linux```

It's a Raspberry Pi 4 with Raspberry Pi OS based on Debian 13.

**Comment by ncw** [comment]
Ah that is great - working in go1.25 broken in go1.26 means we can bisect it. To make a good upstream Go bug report if you've got the time we should attempt to find the commit that broke Go using `git bisect`. I got Claude to make some docs (tweaked by me) on how to do this - I don't know whether you have done `git bisect` before but if not this should help.

## Bisecting the Go regression on your Raspberry Pi

We've confirmed rclone built with **Go 1.25 is fine** and **Go 1.26 corrupts memory** on 32-bit ARM. This finds the exact Go commit that introduced it, which turns this into an actionable bug report for the Go team.

**Before you start:**
- It's ~12–14 cycles of "build the Go toolchain + build rclone + run for a bit". On a Pi 4 expect roughly **15–25 min per cycle**, so **a few hours total** — but it's fully automated, so kick it off and walk away.
- Run it inside `tmux` or `screen` so it survives a disconnected SSH session.
- You'll need a few GB of free disk and a working internet connection.

### 1. Note your bootstrap Go

You need a working Go ≥ 1.22.6 to build the toolchain from source.

You can instal it from here https://go.dev/doc/install

```bash
# with your new go installation
go version        # confirm it says > go1.25.x
go env GOROOT     # note this path, e.g. /usr/local/go or /usr/lib/go-1.25
```

Remember that GOROOT path — it goes in the script below as `BOOT`.

### 2. Clone the Go source

```bash
cd ~
git clone https://go.googlesource.com/go go-bisect
cd go-bisect
git fetch --tags
```

### 3. Create the test script

Save this as `~/bisect-test.sh` (**outside the Go checkout**, so bisect's checkouts don't touch it). Edit the three values in the `configure` block to match your setup — especially `REPRO`, which should be the **exact rclone command that crashes for you**.

```bash
#!/usr/bin/env bash
# Run by `git bisect run` from inside the go-bisect tree.
# Exit: 0 = good (no crash), 1 = bad (crash), 125 = skip (couldn't test).
set -u

# ---------- configure ----------
BOOT="/usr/local/go"                       # GOROOT of your working Go 1.25 (from step 1)
RCLONE_SRC="$HOME/rclone"                  # your rclone source checkout
TEST_SECONDS=300                           # let a non-crashing run go this long, then call it good
REPRO=( sync "/home/pi/data" "Proton Drive:backup" \
        --backup-dir "Proton Drive:Trash" --stats 1m -vv )   # <-- your crashing command
# --------------------------------

export GOTOOLCHAIN=local                   # never auto-download a different toolchain
GOROOT_TREE="$(pwd)"                        # git bisect runs us from the repo root

echo "===> building Go toolchain at $(git rev-parse --short HEAD)"
( cd src && unset GOROOT && GOROOT_BOOTSTRAP="$BOOT" ./make.bash ) \
    || { echo "toolchain build failed → skip"; exit 125; }

GO="$GOROOT_TREE/bin/go"
echo "===> building rclone with $("$GO" version)"
( cd "$RCLONE_SRC" && "$GO" build -o /tmp/rclone-bisect . ) \
    || { echo "rclone build failed → skip"; exit 125; }

echo "===> running reproducer for up to ${TEST_SECONDS}s"
LOG=/tmp/rclone-bisect.log
timeout "${TEST_SECONDS}" /tmp/rclone-bisect "${REPRO[@]}" >"$LOG" 2>&1
rc=$?

if grep -qE "fatal error|found pointer to free object|found bad pointer in Go heap|SIGSEGV|runtime: " "$LOG"; then
    echo "===> CRASH detected → bad"; exit 1
fi
if [ "$rc" -gt 128 ]; then
    echo "===> died with signal $((rc-128)) → bad"; exit 1
fi
if [ "$rc" -eq 124 ]; then
    echo "===> survived ${TEST_SECONDS}s, no crash → good"; exit 0
fi
if [ "$rc" -eq 0 ]; then
    echo "===> completed cleanly → good"; exit 0
fi
echo "===> exited $rc with no crash signature (network/auth?) → skip"; exit 125
```

Make it executable:

```bash
chmod +x ~/bisect-test.sh
```

### 4. Sanity-check the two endpoints first

This validates your script and tags before committing to the full run. From inside `~/go-bisect`:

```bash
git checkout go1.26.3 && ~/bisect-test.sh ; echo "exit=$?"   # expect: CRASH → bad, exit=1
git checkout go1.25.0 && ~/bisect-test.sh ; echo "exit=$?"   # expect: good,       exit=0
```

If those two don't come out as **bad** and **good** respectively, stop and tell us — the script or the reproducer needs adjusting (don't bisect on a flaky test).

### 5. Run the automated bisect

```bash
cd ~/go-bisect
git bisect start
git bisect bad  go1.26.3
git bisect good go1.25.0
git bisect run ~/bisect-test.sh
```

Now wait. `git bisect run` will build/test each midpoint automatically, using your script's exit codes to decide good/bad/skip, and narrow down to the culprit.

### 6. Read off the result

When it finishes it prints something like:

```
<40-hex-commit> is the first bad commit
```

Capture the full details and clean up:

```bash
git bisect log > ~/bisect-log.txt          # the full decision trail
git show --stat <first-bad-commit>         # what the commit changed
git bisect reset
```

Send us **`~/bisect-log.txt`** and the first-bad-commit hash (the `git show` output too) — that's the gold for the Go team.

### Troubleshooting

- **A cycle says "skip"** (toolchain or rclone failed to build, or a transient network/auth error): that's normal — `git bisect run` just moves on and tries to route around it.
- **Inconsistent results** (a "good" that you suspect should be bad): increase `TEST_SECONDS`, or run the reproducer in a loop. The crash is timing/GC-dependent, so giving it longer reduces false "good" verdicts.
- **Low on disk**: run `go clean -cache` occasionally — each toolchain produces its own build-cache entries for rclone.
- **OOM during `make.bash`**: prefix it with `GOMAXPROCS=2` to reduce build parallelism.
- **To pause and resume**: `git bisect log > save.txt`, later `git bisect replay save.txt`.

**Comment by ncw** [comment]
Actually looking at the script again that should force the 32 bit build so under `export GOTOOLCHAIN=local`

Add

```
export GOARCH=arm
export GOARM=7
```

Thanks

**Comment by massoncl** [comment]
I tried doing the bisect but I am having issues with the rclone build. The two test cases (for the known good and bad commits) work as expected, but when I run the git bisect, all the rclone builds fail. 

I ran the build manually, I get a single line of output 

```# golang.org/x/crypto/chacha20poly1305
../go/pkg/mod/golang.org/x/crypto@v0.52.0/chacha20poly1305/fips140only_go1.26.go:11:46: undefined: fips140.Enforced
```

and after a while the process exits with exit code 1, and the binary is not created. 

I'm not sure what's going on and I don't know if I'll have more time to debug this

**Comment by ncw** [comment]
OK thanks for trying @massoncl :-)

If I have time I'll try to repro this on my raspberry pi.

I'll close this - I think we've resolved the rclone problem by using the 64 bit binary on the 64 bit OS.
